# Generated by Django 4.0.1 on 2022-02-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsApp', '0003_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.TextField(default='admin', max_length=50),
        ),
    ]
