# Generated by Django 4.0.1 on 2022-02-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='issuper',
            field=models.BooleanField(default=False),
        ),
    ]
