# Generated by Django 4.0.1 on 2022-02-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuserApp', '0002_myuser_issuper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='issuper',
        ),
    ]
