# Generated by Django 4.0.1 on 2022-02-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuserApp', '0004_rename_name_myuser_username_myuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.TextField(max_length=50),
        ),
    ]
